SELECT Name, Gender, Salary, LAST_VALUE(Name) OVER (ORDER BY Salary) AS [LAST_VALUE] FROM tblEmployee;

SELECT Name, Gender, Salary, LAST_VALUE(Name) OVER (ORDER BY Salary ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS [LAST_VALUE] FROM tblEmployee;

SELECT Name, Gender, Salary, LAST_VALUE(Name) OVER (ORDER BY Salary ROWS BETWEEN UNBOUNDED PRECEDING AND UNBOUNDED FOLLOWING) AS [LAST_VALUE] FROM tblEmployee;

SELECT Name, Gender, Salary, LAST_VALUE(Name) OVER (PARTITION BY Gender ORDER BY Salary ROWS BETWEEN UNBOUNDED PRECEDING AND UNBOUNDED FOLLOWING) AS [LAST_VALUE] FROM tblEmployee;