SELECT EOMONTH('02/20/2021') AS LastDay;
SELECT EOMONTH('02/20/2020') AS LastDay;
SELECT EOMONTH(GETDATE());

SELECT EOMONTH(GETDATE(), 2);
SELECT EOMONTH(GETDATE(), -1);

SELECT Name, DateOfBirth, EOMONTH(DateOfBirth) FROM tblEmployee;
SELECT Name, DateOfBirth, DATEPART(DD, EOMONTH(DateOfBirth)) FROM tblEmployee;