DECLARE @MyGuid UNIQUEIDENTIFIER;
SET @MyGuid = NEWID();
IF(@MyGuid IS NULL) BEGIN
	PRINT('@MyGuid is null.');
END
ELSE BEGIN
	PRINT('@MyGuid is not null.');
END;

DECLARE @MyGuid UNIQUEIDENTIFIER;
IF(@MyGuid IS NULL) BEGIN
	SET @MyGuid = NEWID();
END
ELSE BEGIN
	PRINT('@MyGuid is not null.');
END;
SELECT @MyGuid;

SELECT ISNULL(@MyGuid, NEWID());

-- Creating empty Guid.
SELECT CAST(CAST(0 AS BINARY) AS UNIQUEIDENTIFIER);
SELECT CAST(0x0 AS UNIQUEIDENTIFIER);

DECLARE @MyGuid UNIQUEIDENTIFIER;
SET @MyGuid = CAST(0x0 AS UNIQUEIDENTIFIER);;
--IF(@MyGuid = '00000000-0000-0000-0000-000000000000') BEGIN
--IF(@MyGuid = CAST(CAST(0 AS BINARY) AS UNIQUEIDENTIFIER)) BEGIN
IF(@MyGuid = CAST(0x0 AS UNIQUEIDENTIFIER)) BEGIN
	PRINT('Guid is empty.');
END
ELSE BEGIN
	PRINT('Guid is not empty.');
END;