CREATE TRIGGER trRollbackAllDDL
ON DATABASE FOR CREATE_TABLE, ALTER_TABLE, DROP_TABLE
AS BEGIN
	ROLLBACK; 
	PRINT 'Cannot create, alter or drop a table.';
END;

CREATE TRIGGER trRollbackAllServerDDL
ON ALL SERVER FOR CREATE_TABLE, ALTER_TABLE, DROP_TABLE
AS BEGIN
	ROLLBACK; 
	PRINT 'Cannot create, alter or drop a table.';
END;

CREATE TABLE FOO(Id INT);
DROP TABLE FOO;

USE TestSample
GO
CREATE TABLE FOO(Id INT);
DROP TABLE FOO;

DISABLE TRIGGER trRollbackAllServerDDL ON ALL SERVER;
ENABLE TRIGGER trRollbackAllServerDDL ON ALL SERVER;
DROP TRIGGER trRollbackAllServerDDL ON ALL SERVER;